# Generated by Django 3.0.2 on 2020-02-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='client_id',
            field=models.IntegerField(default='', max_length=100),
        ),
    ]
