# Generated by Django 3.0.2 on 2020-02-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_one', '0002_question_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='client_id',
            field=models.IntegerField(),
        ),
    ]
