# Generated by Django 3.0.2 on 2020-02-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_one', '0003_auto_20200206_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='client_id',
            field=models.IntegerField(null=True),
        ),
    ]
