# Generated by Django 3.0.2 on 2020-02-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_one', '0004_auto_20200206_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='client_id',
        ),
        migrations.AddField(
            model_name='question',
            name='client_ID',
            field=models.IntegerField(default=True),
        ),
    ]
