# Generated by Django 3.0.2 on 2020-02-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_one', '0005_auto_20200206_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='client_ID',
            new_name='client_no',
        ),
    ]
