# Generated by Django 3.0.2 on 2020-02-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_one', '0007_auto_20200206_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='client_num',
        ),
    ]
