# Generated by Django 3.0.2 on 2020-02-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_one', '0011_auto_20200206_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='client_id',
        ),
        migrations.AddField(
            model_name='question',
            name='client_num',
            field=models.IntegerField(default=0),
        ),
    ]
