# Generated by Django 3.0.2 on 2020-02-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_one', '0012_auto_20200206_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='client_num',
        ),
    ]
