# Generated by Django 3.0.2 on 2020-02-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_one', '0013_remove_question_client_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='field',
            field=models.IntegerField(default=0),
        ),
    ]
